import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import i18next from "i18next";
import { initReactI18next } from "react-i18next";

const savedLng =
  (typeof localStorage !== "undefined" && localStorage.getItem("lang")) || "en";

i18next.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        common: {
          dashboard: "Dashboard",
          tracking: "Tracking",
          settings: "Settings",
          signOut: "Sign out",
          themeToggle: "Toggle Theme",
          email: "Email",
          password: "Password",
          signIn: "Sign In",
          signingIn: "Signing in...",
          admin: "Admin",
          adminUser: "Admin User",
          english: "English",
          french: "French",
          spanish: "Spanish",
          german: "German",
          arabic: "Arabic",
          japanese: "Japanese",
        },
        settings: {
          title: "Settings",
          profile: "Profile",
          security: "Security",
          preferences: "Preferences",
          displayName: "Display Name",
          changePassword: "Change Password",
          avatar: "Avatar",
          save: "Save",
        },
        tracking: {
          title: "Tracking",
          incomingTickets: "Incoming Tickets",
          conversation: "Conversation",
          selectTicket: "Select a ticket to view messages",
          send: "Send",
        },
        dashboard: {
          title: "User Management Dashboard",
        },
        login: {
          title: "Admin Login",
          subtitle: "Access the user management dashboard",
          emailPlaceholder: "admin@example.com",
          passwordPlaceholder: "Enter your password",
          successTitle: "Login Successful",
          successDesc: "Welcome to the admin dashboard",
          failedTitle: "Login Failed",
          failedDesc: "Invalid credentials or insufficient permissions",
        },
        notFound: {
          title: "404 Page Not Found",
          hint: "Did you forget to add the page to the router?",
        },
      },
    },
    fr: {
      translation: {
        common: {
          dashboard: "Tableau de bord",
          tracking: "Suivi",
          settings: "Paramètres",
          signOut: "Se déconnecter",
          themeToggle: "Changer le thème",
          email: "E-mail",
          password: "Mot de passe",
          signIn: "Se connecter",
          signingIn: "Connexion...",
          admin: "Admin",
          adminUser: "Utilisateur Admin",
          english: "Anglais",
          french: "Français",
          spanish: "Espagnol",
          german: "Allemand",
          arabic: "Arabe",
          japanese: "Japonais",
        },
        settings: {
          title: "Paramètres",
          profile: "Profil",
          security: "Sécurité",
          preferences: "Préférences",
          displayName: "Nom d'affichage",
          changePassword: "Changer le mot de passe",
          avatar: "Avatar",
          save: "Enregistrer",
        },
        tracking: {
          title: "Suivi",
          incomingTickets: "Tickets entrants",
          conversation: "Conversation",
          selectTicket: "Sélectionnez un ticket pour voir les messages",
          send: "Envoyer",
        },
        dashboard: {
          title: "Tableau de gestion des utilisateurs",
        },
        login: {
          title: "Connexion Admin",
          subtitle: "Accéder au tableau de gestion des utilisateurs",
          emailPlaceholder: "admin@exemple.com",
          passwordPlaceholder: "Entrez votre mot de passe",
          successTitle: "Connexion réussie",
          successDesc: "Bienvenue sur le tableau de bord",
          failedTitle: "Échec de la connexion",
          failedDesc: "Identifiants invalides ou autorisations insuffisantes",
        },
        notFound: {
          title: "404 Page introuvable",
          hint: "Avez-vous oublié d'ajouter la page au routeur ?",
        },
      },
    },
    es: {
      translation: {
        common: {
          dashboard: "Tablero",
          tracking: "Seguimiento",
          settings: "Configuración",
          signOut: "Cerrar sesión",
          themeToggle: "Cambiar tema",
          email: "Correo electrónico",
          password: "Contraseña",
          signIn: "Iniciar sesión",
          signingIn: "Iniciando...",
          admin: "Admin",
          adminUser: "Usuario Admin",
          english: "Inglés",
          french: "Francés",
          spanish: "Español",
          german: "Alemán",
          arabic: "Árabe",
          japanese: "Japonés",
        },
        settings: {
          title: "Configuración",
          profile: "Perfil",
          security: "Seguridad",
          preferences: "Preferencias",
          displayName: "Nombre para mostrar",
          changePassword: "Cambiar contraseña",
          avatar: "Avatar",
          save: "Guardar",
        },
        tracking: {
          title: "Seguimiento",
          incomingTickets: "Tickets entrantes",
          conversation: "Conversación",
          selectTicket: "Seleccione un ticket para ver los mensajes",
          send: "Enviar",
        },
        dashboard: { title: "Panel de gestión de usuarios" },
        login: {
          title: "Inicio de sesión de administrador",
          subtitle: "Accede al panel de gestión de usuarios",
          emailPlaceholder: "admin@ejemplo.com",
          passwordPlaceholder: "Introduce tu contraseña",
          successTitle: "Inicio de sesión exitoso",
          successDesc: "Bienvenido al panel de administración",
          failedTitle: "Error de inicio de sesión",
          failedDesc: "Credenciales inválidas o permisos insuficientes",
        },
        notFound: {
          title: "404 Página no encontrada",
          hint: "¿Olvidaste añadir la página al router?",
        },
      },
    },
    de: {
      translation: {
        common: {
          dashboard: "Dashboard",
          tracking: "Verfolgung",
          settings: "Einstellungen",
          signOut: "Abmelden",
          themeToggle: "Theme umschalten",
          email: "E‑Mail",
          password: "Passwort",
          signIn: "Anmelden",
          signingIn: "Anmeldung...",
          admin: "Admin",
          adminUser: "Admin Benutzer",
          english: "Englisch",
          french: "Französisch",
          spanish: "Spanisch",
          german: "Deutsch",
          arabic: "Arabisch",
          japanese: "Japanisch",
        },
        settings: {
          title: "Einstellungen",
          profile: "Profil",
          security: "Sicherheit",
          preferences: "Voreinstellungen",
          displayName: "Anzeigename",
          changePassword: "Passwort ändern",
          avatar: "Avatar",
          save: "Speichern",
        },
        tracking: {
          title: "Verfolgung",
          incomingTickets: "Eingehende Tickets",
          conversation: "Konversation",
          selectTicket: "Wählen Sie ein Ticket, um Nachrichten zu sehen",
          send: "Senden",
        },
        dashboard: { title: "Benutzerverwaltungs‑Dashboard" },
        login: {
          title: "Admin‑Anmeldung",
          subtitle: "Greifen Sie auf das Benutzerverwaltungs‑Dashboard zu",
          emailPlaceholder: "admin@beispiel.com",
          passwordPlaceholder: "Geben Sie Ihr Passwort ein",
          successTitle: "Anmeldung erfolgreich",
          successDesc: "Willkommen im Admin‑Dashboard",
          failedTitle: "Anmeldung fehlgeschlagen",
          failedDesc: "Ungültige Anmeldedaten oder unzureichende Berechtigungen",
        },
        notFound: {
          title: "404 Seite nicht gefunden",
          hint: "Haben Sie die Seite im Router hinzugefügt?",
        },
      },
    },
    ar: {
      translation: {
        common: {
          dashboard: "لوحة التحكم",
          tracking: "التذاكر",
          settings: "الإعدادات",
          signOut: "تسجيل الخروج",
          themeToggle: "تغيير النمط",
          email: "البريد الإلكتروني",
          password: "كلمة المرور",
          signIn: "تسجيل الدخول",
          signingIn: "جاري تسجيل الدخول...",
          admin: "المشرف",
          adminUser: "مستخدم المشرف",
          english: "الإنجليزية",
          french: "الفرنسية",
          spanish: "الإسبانية",
          german: "الألمانية",
          arabic: "العربية",
          japanese: "اليابانية",
        },
        settings: {
          title: "الإعدادات",
          profile: "الملف الشخصي",
          security: "الأمان",
          preferences: "التفضيلات",
          displayName: " اسم العرض",
          changePassword: "تغيير كلمة المرور",
          avatar: "الصورة",
          save: "حفظ",
        },
        tracking: {
          title: "التذاكر",
          incomingTickets: "التذاكر الواردة",
          conversation: "المحادثة",
          selectTicket: "اختر تذكرة لعرض الرسائل",
          send: "إرسال",
        },
        dashboard: { title: "لوحة إدارة المستخدمين" },
        login: {
          title: "تسجيل دخول المشرف",
          subtitle: "الوصول إلى لوحة إدارة المستخدمين",
          emailPlaceholder: "admin@example.com",
          passwordPlaceholder: "أدخل كلمة المرور",
          successTitle: "تم تسجيل الدخول بنجاح",
          successDesc: "مرحبًا بك في لوحة المشرف",
          failedTitle: "فشل تسجيل الدخول",
          failedDesc: "بيانات اعتماد غير صالحة أو صلاحيات غير كافية",
        },
        notFound: {
          title: "404 الصفحة غير موجودة",
          hint: "هل نسيت إضافة الصفحة إلى الموجه؟",
        },
      },
    },
    ja: {
      translation: {
        common: {
          dashboard: "ダッシュボード",
          tracking: "チケット",
          settings: "設定",
          signOut: "サインアウト",
          themeToggle: "テーマ切替",
          email: "メール",
          password: "パスワード",
          signIn: "サインイン",
          signingIn: "サインイン中...",
          admin: "管理者",
          adminUser: "管理者ユーザー",
          english: "英語",
          french: "フランス語",
          spanish: "スペイン語",
          german: "ドイツ語",
          arabic: "アラビア語",
          japanese: "日本語",
        },
        settings: {
          title: "設定",
          profile: "プロフィール",
          security: "セキュリティ",
          preferences: "環境設定",
          displayName: "表示名",
          changePassword: "パスワード変更",
          avatar: "アバター",
          save: "保存",
        },
        tracking: {
          title: "チケット",
          incomingTickets: "受信チケット",
          conversation: "会話",
          selectTicket: "メッセージを見るにはチケットを選択してください",
          send: "送信",
        },
        dashboard: { title: "ユーザー管理ダッシュボード" },
        login: {
          title: "管理者ログイン",
          subtitle: "ユーザー管理ダッシュボードにアクセス",
          emailPlaceholder: "admin@example.com",
          passwordPlaceholder: "パスワードを入力",
          successTitle: "ログイン成功",
          successDesc: "管理ダッシュボードへようこそ",
          failedTitle: "ログイン失敗",
          failedDesc: "無効な認証情報または権限不足",
        },
        notFound: {
          title: "404 ページが見つかりません",
          hint: "ルーターにページを追加しましたか？",
        },
      },
    },
  },
  lng: savedLng,
  fallbackLng: "en",
  interpolation: { escapeValue: false },
});

const applyDir = (lng: string) => {
  document.documentElement.dir = lng === "ar" ? "rtl" : "ltr";
};
applyDir(savedLng);
i18next.on("languageChanged", applyDir);

createRoot(document.getElementById("root")!).render(<App />);